import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  contributorSidebar: [
    'README',
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows',
        },
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        {
          type: 'autogenerated',
          dirName: 'troubleshooting',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quick Start',
      items: [
        {
          type: 'autogenerated',
          dirName: 'quick-start',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plans',
      items: [
        {
          type: 'autogenerated',
          dirName: 'plans',
        },
      ],
    },
  ],
};

export default sidebars; 