const std = @import("std");

pub const Token = struct {
    tag: Tag,
    loc: Loc,

    pub const Loc = struct {
        start: u32,
        end: u32,
    };

    pub fn slice(self: Token, source: []const u8) []const u8 {
        return source[self.loc.start..self.loc.end];
    }
};

pub const Tag = enum {
    // Literals
    int_literal,
    float_literal,
    string_literal,
    char_literal,
    identifier,

    // Delimiters
    lparen,
    rparen,
    lbrace,
    rbrace,
    lbracket,
    rbracket,
    semicolon,
    colon,
    comma,
    dot,
    hash_lbracket, // #[

    // Operators
    plus,
    minus,
    star,
    slash,
    percent,
    ampersand,
    pipe,
    caret,
    tilde,
    bang,
    equal,
    double_equal,
    bang_equal,
    less,
    less_equal,
    greater,
    greater_equal,
    shift_left,
    shift_right,
    double_ampersand,
    double_pipe,
    arrow, // ->
    double_colon, // ::

    // Keywords
    keyword_package,
    keyword_import,
    keyword_as,
    keyword_fn,
    keyword_let,
    keyword_const,
    keyword_mut,
    keyword_if,
    keyword_else,
    keyword_for,
    keyword_in,
    keyword_match,
    keyword_return,
    keyword_break,
    keyword_continue,
    keyword_pub,
    keyword_priv,
    keyword_struct,
    keyword_enum,
    keyword_impl,
    keyword_self,
    keyword_extern,
    keyword_unsafe,
    keyword_spawn,
    keyword_spawn_with_handle,
    keyword_await,
    keyword_sizeof,
    keyword_void,
    keyword_none,
    keyword_true,
    keyword_false,

    // Built-in type keywords
    keyword_Result,
    keyword_Option,
    keyword_Never,
    keyword_int,
    keyword_float,
    keyword_bool,
    keyword_string,
    keyword_usize,
    keyword_isize,
    keyword_i8,
    keyword_i16,
    keyword_i32,
    keyword_i64,
    keyword_i128,
    keyword_u8,
    keyword_u16,
    keyword_u32,
    keyword_u64,
    keyword_u128,
    keyword_f32,
    keyword_f64,

    // Special
    eof,
    invalid,

    pub fn isTypeKeyword(self: Tag) bool {
        return switch (self) {
            .keyword_int,
            .keyword_float,
            .keyword_bool,
            .keyword_string,
            .keyword_usize,
            .keyword_isize,
            .keyword_i8,
            .keyword_i16,
            .keyword_i32,
            .keyword_i64,
            .keyword_i128,
            .keyword_u8,
            .keyword_u16,
            .keyword_u32,
            .keyword_u64,
            .keyword_u128,
            .keyword_f32,
            .keyword_f64,
            .keyword_void,
            .keyword_Never,
            .keyword_Result,
            .keyword_Option,
            => true,
            else => false,
        };
    }
};

pub const keywords = std.StaticStringMap(Tag).initComptime(.{
    .{ "package", .keyword_package },
    .{ "import", .keyword_import },
    .{ "as", .keyword_as },
    .{ "fn", .keyword_fn },
    .{ "let", .keyword_let },
    .{ "const", .keyword_const },
    .{ "mut", .keyword_mut },
    .{ "if", .keyword_if },
    .{ "else", .keyword_else },
    .{ "for", .keyword_for },
    .{ "in", .keyword_in },
    .{ "match", .keyword_match },
    .{ "return", .keyword_return },
    .{ "break", .keyword_break },
    .{ "continue", .keyword_continue },
    .{ "pub", .keyword_pub },
    .{ "priv", .keyword_priv },
    .{ "struct", .keyword_struct },
    .{ "enum", .keyword_enum },
    .{ "impl", .keyword_impl },
    .{ "self", .keyword_self },
    .{ "extern", .keyword_extern },
    .{ "unsafe", .keyword_unsafe },
    .{ "spawn", .keyword_spawn },
    .{ "spawn_with_handle", .keyword_spawn_with_handle },
    .{ "await", .keyword_await },
    .{ "sizeof", .keyword_sizeof },
    .{ "void", .keyword_void },
    .{ "none", .keyword_none },
    .{ "true", .keyword_true },
    .{ "false", .keyword_false },
    .{ "Result", .keyword_Result },
    .{ "Option", .keyword_Option },
    .{ "Never", .keyword_Never },
    .{ "int", .keyword_int },
    .{ "float", .keyword_float },
    .{ "bool", .keyword_bool },
    .{ "string", .keyword_string },
    .{ "usize", .keyword_usize },
    .{ "isize", .keyword_isize },
    .{ "i8", .keyword_i8 },
    .{ "i16", .keyword_i16 },
    .{ "i32", .keyword_i32 },
    .{ "i64", .keyword_i64 },
    .{ "i128", .keyword_i128 },
    .{ "u8", .keyword_u8 },
    .{ "u16", .keyword_u16 },
    .{ "u32", .keyword_u32 },
    .{ "u64", .keyword_u64 },
    .{ "u128", .keyword_u128 },
    .{ "f32", .keyword_f32 },
    .{ "f64", .keyword_f64 },
});

pub fn getKeyword(bytes: []const u8) ?Tag {
    return keywords.get(bytes);
}
