name: Asthra BDD Tests

on:
  workflow_call:

# This workflow now uses the simplified approach with run-bdd-tests-local.sh
# The implementation has been moved to bdd-implementation.yml for better maintainability
jobs:
  call-simplified-workflow:
    uses: ./.github/workflows/bdd-implementation.yml