name: Asthra Build and Test

on:
  workflow_call:
    inputs:
      run_performance_tests:
        description: 'Run performance benchmarks'
        required: false
        default: false
        type: boolean
      run_sanitizer_tests:
        description: 'Run sanitizer tests'
        required: false
        default: true
        type: boolean

env:
  ASTHRA_VERSION: "0.1.0"
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.platform }}, ${{ matrix.compiler }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'arm64' && matrix.platform == 'linux' && 'ubuntu-24.04-arm' || matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds - Clang only
          - platform: linux
            os: ubuntu-24.04
            compiler: clang
            arch: x64
            cc: clang
            cxx: clang++
            build_type: Release
            
          # Linux ARM64 builds - Clang only
          - platform: linux
            os: ubuntu-24.04
            compiler: clang
            arch: arm64
            cc: clang
            cxx: clang++
            build_type: Release
            
          # macOS builds - Clang only
          - platform: macos
            os: macos-14
            compiler: clang
            arch: arm64
            cc: clang
            cxx: clang++
            build_type: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # =============================================================================
    # PLATFORM-SPECIFIC SETUP
    # =============================================================================
            
    - name: Setup Linux dependencies
      if: matrix.platform == 'linux'
      run: |
        set -e
        echo "=== Installing Linux Dependencies ==="
        
        # Update package lists
        sudo apt-get update -y
        
        # Install build essentials and development tools
        sudo apt-get install -y \
          build-essential \
          cmake \
          libc6-dev \
          pkg-config \
          gperf \
          wget \
          software-properties-common
        
        # Install LLVM 18 (required)
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main"
        sudo apt-get update -y
        sudo apt-get install -y llvm-18 llvm-18-dev clang-18 lld-18 llvm-18-tools
        
        # Verify LLVM 18 tools exist
        echo "Checking LLVM 18 tools..."
        ls -la /usr/bin/lld-18 || echo "lld-18 not found"
        ls -la /usr/bin/llvm-ar-18 || echo "llvm-ar-18 not found"
        ls -la /usr/bin/llvm-ranlib-18 || echo "llvm-ranlib-18 not found"
        
        # Verify installation
        echo "Checking clang-18 version..."
        which clang-18 && clang-18 --version
        
        # Install optional dependencies (non-critical)
        sudo apt-get install -y valgrind || echo "Valgrind not available"
        sudo apt-get install -y libjson-c-dev || echo "json-c package not available, CMake will handle it"
        
        echo "✓ Linux dependencies installed successfully"
          
    - name: Setup macOS dependencies
      if: matrix.platform == 'macos'
      run: |
        set -e
        echo "=== Installing macOS Dependencies ==="
        # Don't update brew, just install what we need
        brew install \
          cmake \
          pkg-config \
          gperf \
          llvm@18 \
          json-c || echo "Some packages may already be installed"
        
        # Add LLVM to PATH
        echo "/opt/homebrew/opt/llvm@18/bin" >> $GITHUB_PATH
        echo "LDFLAGS=-L/opt/homebrew/opt/llvm@18/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/homebrew/opt/llvm@18/include" >> $GITHUB_ENV
        
        echo "✓ macOS dependencies installed successfully"
          
    # =============================================================================
    # COMPILER SETUP
    # =============================================================================
    
    - name: Set compiler environment
      shell: bash
      run: |
        echo "=== Setting Compiler Environment ==="
        
        # Set compiler environment
        if [[ "${{ matrix.platform }}" == "linux" ]]; then
          echo "Using clang-18 on Linux"
          echo "CC=clang-18" >> $GITHUB_ENV
          echo "CXX=clang++-18" >> $GITHUB_ENV
          CC_TO_USE="clang-18"
          CXX_TO_USE="clang++-18"
        elif [[ "${{ matrix.platform }}" == "macos" ]]; then
          # macOS: Use LLVM 18 from homebrew
          if [[ -x "/opt/homebrew/opt/llvm@18/bin/clang" ]]; then
            echo "CC=/opt/homebrew/opt/llvm@18/bin/clang" >> $GITHUB_ENV
            echo "CXX=/opt/homebrew/opt/llvm@18/bin/clang++" >> $GITHUB_ENV
            CC_TO_USE="/opt/homebrew/opt/llvm@18/bin/clang"
            CXX_TO_USE="/opt/homebrew/opt/llvm@18/bin/clang++"
          else
            echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
            echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
            CC_TO_USE="${{ matrix.cc }}"
            CXX_TO_USE="${{ matrix.cxx }}"
          fi
        else
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
          CC_TO_USE="${{ matrix.cc }}"
          CXX_TO_USE="${{ matrix.cxx }}"
        fi
        
        # Verify compilers are available
        echo "Verifying C compiler: $CC_TO_USE"
        $CC_TO_USE --version
        echo "Verifying C++ compiler: $CXX_TO_USE"
        $CXX_TO_USE --version
        
        echo "✓ Compiler environment set successfully"
    
    - name: Verify LLVM installation
      shell: bash
      run: |
        echo "=== Verifying LLVM Installation ==="
        
        # Find llvm-config on Unix-like systems
        if command -v llvm-config-18 >/dev/null 2>&1; then
          echo "Found llvm-config-18"
          llvm-config-18 --version
          echo "LLVM_CONFIG=llvm-config-18" >> $GITHUB_ENV
        elif command -v llvm-config >/dev/null 2>&1; then
          echo "Found llvm-config"
          llvm-config --version
          echo "LLVM_CONFIG=llvm-config" >> $GITHUB_ENV
        else
          echo "ERROR: LLVM not found!"
          exit 1
        fi
        
        echo "✓ LLVM verified successfully"

    # =============================================================================
    # BUILD INFORMATION
    # =============================================================================
    
    - name: Display build information
      shell: bash
      run: |
        echo "=== Build Information ==="
        echo "Platform: ${{ matrix.platform }}"
        echo "OS: ${{ matrix.os }}"
        echo "Compiler: ${{ matrix.compiler }}"
        echo "Architecture: ${{ matrix.arch }}"
        echo "Build Type: ${{ matrix.build_type }}"
        echo ""
        echo "=== Compiler Information ==="
        ${CC} --version || true
        echo ""
        echo "=== CMake Information ==="
        cmake --version

    # =============================================================================
    # BUILD
    # =============================================================================
    
    - name: Configure CMake
      shell: bash
      run: |
        echo "=== CMake Configuration ==="
        mkdir -p build
        cd build
        
        echo "Working directory: $(pwd)"
        echo "CMakeLists.txt exists: $(test -f ../CMakeLists.txt && echo 'YES' || echo 'NO')"
        echo "CMAKE_BUILD_TYPE: ${{ matrix.build_type }}"
        echo "CMAKE_C_COMPILER: ${CC}"
        echo "CMAKE_CXX_COMPILER: ${CXX}"
        echo ""
        
        # Use default generator on Unix-like systems
        # For Linux, use LLVM toolchain to avoid version mismatches
        if [[ "${{ matrix.platform }}" == "linux" ]]; then
          # Find LLVM tools
          LLVM_AR_PATH=$(which llvm-ar-18 || which llvm-ar)
          LLVM_RANLIB_PATH=$(which llvm-ranlib-18 || which llvm-ranlib)
          
          echo "Using LLVM AR: $LLVM_AR_PATH"
          echo "Using LLVM RANLIB: $LLVM_RANLIB_PATH"
          
          # Use lld-18 if available, otherwise lld
          if which lld-18 >/dev/null 2>&1; then
            LLD_NAME="lld-18"
          else
            LLD_NAME="lld"
          fi
          echo "Using linker: $LLD_NAME"
          
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER="${CC}" \
            -DCMAKE_CXX_COMPILER="${CXX}" \
            -DCMAKE_AR="$LLVM_AR_PATH" \
            -DCMAKE_RANLIB="$LLVM_RANLIB_PATH" \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=$LLD_NAME" \
            -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=$LLD_NAME" \
            -DCMAKE_MODULE_LINKER_FLAGS="-fuse-ld=$LLD_NAME"
        else
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER="${CC}" \
            -DCMAKE_CXX_COMPILER="${CXX}"
        fi
        
        echo "✓ CMake configuration completed successfully"

    - name: Build Asthra compiler
      shell: bash
      run: |
        echo "=== Building Asthra Compiler ==="
        cd build
        
        echo "Build directory contents before build:"
        ls -la
        echo ""
        
        # Use a reasonable number of parallel jobs
        JOBS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)
        echo "Building with $JOBS parallel jobs"
        
        cmake --build . --config ${{ matrix.build_type }} -j$JOBS
        
        echo "✓ Build completed successfully"

    - name: Verify build artifacts
      shell: bash
      run: |
        echo "=== Verifying Build Artifacts ==="
        
        # Unix-like: Look for files without extension
        if [[ -f "build/asthra" ]]; then
          echo "✓ Asthra compiler built successfully"
          ls -la build/asthra
        elif [[ -f "build/bin/asthra" ]]; then
          echo "✓ Asthra compiler built successfully"
          ls -la build/bin/asthra
        else
          echo "✗ Asthra compiler not found"
          echo "Contents of build directory:"
          find build -name "asthra*" | head -10
          exit 1
        fi

    # =============================================================================
    # BASIC TESTING
    # =============================================================================
    
    - name: Run basic tests
      shell: bash
      run: |
        echo "=== Running Basic Tests ==="
        cd build
        
        JOBS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)
        
        ctest --output-on-failure --parallel $JOBS || echo "Some tests may have failed"

    - name: Test compiler version
      shell: bash
      run: |
        echo "=== Testing Compiler Version ==="
        
        if [[ -f "build/asthra" ]]; then
          ./build/asthra --version || echo "Version command not implemented"
        elif [[ -f "build/bin/asthra" ]]; then
          ./build/bin/asthra --version || echo "Version command not implemented"
        else
          echo "Asthra binary not found for version test"
        fi
        
    - name: Test compiler help
      shell: bash
      run: |
        echo "=== Testing Compiler Help ==="
        
        if [[ -f "build/asthra" ]]; then
          ./build/asthra --help || echo "Help command not implemented"
        elif [[ -f "build/bin/asthra" ]]; then
          ./build/bin/asthra --help || echo "Help command not implemented"
        else
          echo "Asthra binary not found for help test"
        fi

    # =============================================================================
    # SANITIZER TESTS (Optional)
    # =============================================================================
    
    - name: Run sanitizer tests
      if: inputs.run_sanitizer_tests && matrix.platform == 'linux'
      run: |
        echo "=== Running Sanitizer Tests ==="
        # Reconfigure with sanitizers
        cd build
        
        # Find LLVM tools (same as in configure step)
        LLVM_AR_PATH=$(which llvm-ar-18 || which llvm-ar)
        LLVM_RANLIB_PATH=$(which llvm-ranlib-18 || which llvm-ranlib)
        
        # Use lld-18 if available, otherwise lld
        if which lld-18 >/dev/null 2>&1; then
          LLD_NAME="lld-18"
        else
          LLD_NAME="lld"
        fi
        
        cmake .. \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_COMPILER="${CC}" \
          -DCMAKE_CXX_COMPILER="${CXX}" \
          -DCMAKE_AR="$LLVM_AR_PATH" \
          -DCMAKE_RANLIB="$LLVM_RANLIB_PATH" \
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=$LLD_NAME -fsanitize=address,undefined" \
          -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=$LLD_NAME -fsanitize=address,undefined" \
          -DCMAKE_MODULE_LINKER_FLAGS="-fuse-ld=$LLD_NAME -fsanitize=address,undefined" \
          -DCMAKE_C_FLAGS="-fsanitize=address,undefined" \
          -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined"
        
        cmake --build . --config Debug
        ctest --output-on-failure || echo "Sanitizer tests may have failed"

    # =============================================================================
    # PERFORMANCE TESTS (Optional)
    # =============================================================================
    
    - name: Run performance benchmarks
      if: inputs.run_performance_tests && matrix.platform == 'linux'
      run: |
        echo "=== Running Performance Benchmarks ==="
        cd build
        # Look for benchmark targets
        cmake --build . --target benchmark 2>/dev/null || echo "No benchmark target available"

    # =============================================================================
    # ARTIFACT COLLECTION
    # =============================================================================
    
    - name: Collect build artifacts
      if: always()
      shell: bash
      run: |
        echo "=== Collecting Build Artifacts ==="
        mkdir -p artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}
        
        # Copy binaries and libraries
        find build -name "asthra*" -type f -executable -exec cp {} artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}/ \; 2>/dev/null || true
        find build -name "*.a" -exec cp {} artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}/ \; 2>/dev/null || true
        find build -name "*.so" -exec cp {} artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}/ \; 2>/dev/null || true
        
        # Copy logs
        cp *.log artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}/ 2>/dev/null || true
        
        echo "Artifacts collected:"
        ls -la artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}/
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: asthra-${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}
        path: artifacts/${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.arch }}/
        retention-days: 7
