name: Asthra Cross-Platform Compatibility

on:
  workflow_call:

jobs:
  cross-platform-compatibility:
    name: Cross-Platform Compatibility
    runs-on: ubuntu-22.04
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-artifacts
        
    - name: Analyze cross-platform compatibility
      shell: bash
      run: |
        echo "=== Cross-Platform Compatibility Analysis ==="
        echo "Available artifacts:"
        find all-artifacts -type f -name "asthra*" | sort
        
        echo ""
        echo "Platform coverage:"
        ls all-artifacts/ | grep -E "(linux|macos)" | sort
        
        echo ""
        echo "Compiler coverage:"
        ls all-artifacts/ | grep -E "(clang)" | sort 
